name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install --frozen-lockfile
      - name: build
        #        TODO Enable those lines below if you use a Redis cache, you'll also need to configure GitHub Repository Secrets
        #        env:
        #          REDIS_HOST: ${{ secrets.REDIS_HOST }}
        #          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: pnpm build
